# Generated by Django 4.1.10 on 2023-10-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='sid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
