# Generated by Django 4.1.10 on 2023-10-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='sid',
            new_name='id',
        ),
    ]
