# Generated by Django 4.1.10 on 2023-12-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0002_rename_sid_services_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
