# Generated by Django 4.1.10 on 2023-10-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0002_alter_services_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='sid',
            new_name='id',
        ),
    ]
