# Generated by Django 4.1.10 on 2023-11-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffModel',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='provider',
        ),
    ]
