# Generated by Django 4.1.10 on 2023-10-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userProfile',
            field=models.ImageField(upload_to='userProfiles'),
        ),
    ]
