# Generated by Django 4.1.10 on 2023-09-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareapp', '0002_alter_usermodel_first_name_alter_usermodel_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
