# Generated by Django 4.1.10 on 2023-12-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareapp', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('to_staff', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
