# Generated by Django 4.1.10 on 2023-10-04 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareapp', '0002_labtestmodel_passwordtoken_staffmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
