# Generated by Django 4.1.10 on 2023-10-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareapp', '0003_passwordtoken_id_staffmodel_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
