# Generated by Django 4.1.10 on 2023-09-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcareapp', '0005_staffmodel_alter_usermodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cost', models.PositiveIntegerField()),
                ('result_duration', models.PositiveIntegerField()),
            ],
        ),
    ]
