# Generated by Django 4.1.10 on 2023-11-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='resume',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
