# Generated by Django 4.1.10 on 2023-11-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffApp', '0002_remove_staffmodel_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmodel',
            name='specialization',
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='state',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
