# Generated by Django 4.1.10 on 2023-12-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffApp', '0003_remove_staffmodel_specialization_staffmodel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='total_visit',
            field=models.IntegerField(null=True),
        ),
    ]
