# Generated by Django 4.1.10 on 2023-12-01 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffApp', '0004_staffmodel_total_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 1, 21, 2, 33, 848689, tzinfo=datetime.timezone.utc)),
        ),
    ]
